eventsManager:
  className: Phalcon\Events\Manager
  shared: true
  calls:
    - method: enablePriorities
      arguments:
        - { type: parameter, value: true }

stderrLoggerAdapter:
  className: Phalcon\Logger\Adapter\Stream
  arguments:
    - { type: parameter, value: php://stderr }

logger:
  className: Phalcon\Logger\Logger
  shared: true
  arguments:
    - { type: parameter, value: main }
  calls:
    - method: addAdapter
      arguments:
        - { type: parameter, value: stderr }
        - { type: service, name: stderrLoggerAdapter }
    - method: addAdapter
      arguments:
        - { type: parameter, value: profiler }
        - { type: service, name: profilerLoggerAdapter }

db:
  className: Phalcon\Db\Adapter\Pdo\Postgresql
  arguments:
    - type: parameter
      value: !config database
  calls:
    - method: setEventsManager
      arguments:
        - { type: service, name: eventsManager }
