services:
  nginx:
    container_name: profiler-nginx
    restart: unless-stopped
    image: nginx:1.25.0-alpine3.17
    ports:
      - "127.0.0.11:80:80"
      - "127.0.0.11:8080:8080"
    volumes:
      - ./docker/nginx/conf.d/blog.conf:/etc/nginx/conf.d/blog.conf
      - ./docker/nginx/conf.d/micro.conf:/etc/nginx/conf.d/micro.conf
      - ./:/var/www
    depends_on:
      - php

  php:
    container_name: profiler-php
    restart: unless-stopped
    image: srgiz/phalcon-profiler:php${PHP_IMAGE}-phalcon${PHALCON_VERSION}
    build:
      context: docker/php
      args:
        PHP_IMAGE: ${PHP_IMAGE}
        PHALCON_VERSION: ${PHALCON_VERSION}
    environment:
      PS1: "\\u:\\w$$ "
    volumes:
      - ./docker/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./:/var/www

  postgres:
    container_name: profiler-postgres
    restart: unless-stopped
    image: postgres:17.5-alpine3.22
    #ports:
    #  - "127.0.0.11:5432:5432"
    environment:
      POSTGRES_PASSWORD: root
    #volumes:
    #  - profiler-postgres:/var/lib/postgresql/data

networks:
  default:
    name: web-profiler.local
